config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :home, only: :index
  root to: 'home#index'
  namespace :manager do
    resources :products, only: %i[new index edit update show]
    namespace :products do
      resources :pens
      resources :pencils
    end
    resources :orders
    resources :clients
    resource :search_order, only: %i[create]
  end

  namespace :client do
    resources :products, only: %i[new index edit update]
    namespace :products do
      resources :pens
      resources :pencils
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_sets
  belongs_to :client

  validates :product_sets, presence: true
  validates :date_of_saling, presence: true
  validate do |order|
    unless order.date_of_saling > DateTime.current.to_date
      order.errors.add(:date_of_saling, 'Date should be greater now!')
    end
  end

  validate do |order|
    product_ids = order.product_sets.flat_map(&:product_id)

    if product_ids != product_ids.uniq
      order.errors.add(:product_sets, "Please don't use the same products!")
    end
  end

  enum status: %i[opened unreserved reserved closed]

  accepts_nested_attributes_for :product_sets, reject_if: :all_blank, allow_destroy: true
end

app/controllers/manager/clients_controller.rb
class Manager::ClientsController < ManagerController
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def show
    @client = find_client
  end

  def create
    @client = Client.new(**client_params)
    if @client.save
      redirect_to manager_clients_url, notice: 'Client added successfully!'
    else
      render :new
    end
  end

  def edit
    @client = find_client
  end

  def update
    @client = find_client
    if @client.update(**client_params)
      redirect_to manager_clients_url, notice: 'Client updated successfully!'
    else
      render :edit
    end
  end

  def destroy
    @client = find_client
    @client.destroy

    redirect_to manager_clients_url, notice: 'Client destroyed!'
  end

  private

  def client_params
    params.require(:client).permit(:full_name, :phone)
  end

  def find_client
    Client.find(params[:id])
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ManagerController
  def index
    @orders = Order.order(id: :desc).includes(:client, product_sets: { product: :productable })

    if params[:status]
      @orders = @orders.where(status: params[:status])
    else
      @orders = @orders.where.not(status: :closed)
    end

    if params[:search_by_date]
      @orders = @orders.where(date_of_saling: Date.parse(params[:search_by_date]))
    end
  end

  def new
    @order = Order.new
    @products = init_products
    @clients = init_clients
  end

  def create
    @order = Order.new(order_params)
    @clients = init_clients

    if @order.save
      redirect_to manager_orders_url
    else
      @products = init_products
      @clients = init_clients

      flash[:alert] = 'Please add products!' if @order.product_sets.blank?
      error_product_sets = @order.errors[:product_sets].first
      flash[:alert] = error_product_sets if error_product_sets
      render :new
    end
  end

  def show
    @order = Order.includes(product_sets: { product: :productable }).find(params[:id])
  end

  def update
    @order = find_order

    if @order.opened? && %w[unreserved reserved].include?(params[:status]) &&
      !current_user.leader?

      redirect_to manager_orders_url, alert: 'Access denied!'
    end

    ActiveRecord::Base.transaction do
      prev_status = @order.status
      unless @order.opened?
        if @order.update(status: params[:status])
          UpdateAvailableProducts.new(order: @order).call
        else
          flash['alert'] = 'Status invalid!'
        end
      else
        @order.update(status: params[:status])
      end

      if @order.closed? && prev_status == 'reserved'
        @order.product_sets.includes(:product).each do |product_set|
          product = product_set.product
          product.update(sold: product.sold.to_i + product_set.number,
                         in_stock: product.in_stock.to_i - product_set.number)
        end
      end
    end

    redirect_back(fallback_location: manager_orders_url)
  rescue ActiveRecord::RecordInvalid => e
    flash['alert'] = e.message
    redirect_back(fallback_location: manager_orders_url)
  end

  def destroy
    @order = find_order

    @order.destroy

    redirect_to manager_orders_url
  end

  private

  def order_params
    params.require(:order).permit(:'date_of_saling(1i)', :lng, :lat, :client_id,
                                  :'date_of_saling(2i)', :'date_of_saling(3i)',
                                  product_sets_attributes:
                                    [:product_id, :number, :_destroy])
  end

  def find_order
    Order.find(params[:id])
  end

  def init_products
    Product.all.includes(:productable).each_with_object({}) do |product, hash|
      hash[product.productable.attributes_for_select] = product.id
    end
  end

  def init_clients
    Client.all.each_with_object({}) do |client, hash|
      hash[client.attributes_for_select] = client.id
    end
  end
end

app/controllers/manager/products/pencils_controller.rb
class Manager::Products::PencilsController < Manager::ProductsController
  def new
    @pencil = Products::Pencil.new(product: Product.new)
  end

  def create
    @pencil = Products::Pencil.new(
      pencil_params.merge(product: Product.new(product_params))
    )
    if @pencil.product.valid? && @pencil.save
      redirect_to manager_products_url, notice: 'Pencil created successfully!'
    else
      render :new
    end
  end

  def edit
    @pencil = find_pencil
  end

  def update
    @pencil = find_pencil
    if @pencil.update(pencil_params) && @pencil.product.update(product_params)
      flash[:notice] = 'Pencil updated successfully!'
    end

    render :edit
  end

  def destroy
    find_pencil.destroy

    redirect_to manager_products_url, notice: 'Pencil removed successfully!'
  end

  private

  def find_pencil
    Products::Pencil.find(params[:id])
  end

  def pencil_params
    params.require(:products_pencil).permit(:form, :color)
  end

  def product_params
    super(productable_key: :products_pencil)
  end
end

app/controllers/manager/products/pens_controller.rb
class Manager::Products::PensController < Manager::ProductsController
  def new
    @pen = Products::Pen.new(product: Product.new)
  end

  def create
    @pen = Products::Pen.new(pen_params.merge(product: Product.new(product_params)))
    if @pen.product.valid? && @pen.save
      redirect_to manager_products_url, notice: 'Pen created successfully!'
    else
      render :new
    end
  end

  def edit
    @pen = find_pen
  end

  def update
    @pen = find_pen
    ActiveRecord::Base.transaction do
      if @pen.update(pen_params) && @pen.product.update(product_params)
        flash[:notice] = 'Pen updated successfully!'
      end
    end
    render :edit
  end

  def destroy
    find_pen.destroy

    redirect_to manager_products_url, notice: 'Pen removed successfully!'
  end

  private

  def find_pen
    Products::Pen.find(params[:id])
  end

  def pen_params
    params.require(:products_pen).permit(:form, :kernel)
  end

  def product_params
    super(productable_key: :products_pen)
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ManagerController
  def index
    @products = Product.all.includes(:productable)
  end

  def new; end

  def show
    @product = Product.includes(product_sets: { order: :client}).find(params[:id])
  end

  def edit
    @product = find_product
  end

  def update
    @product = find_product

    amount_received = params.dig(:product, :in_stock).to_i
    if Events::UpdateStockOfProduct.new(
        product: @product,
        amount_received: amount_received
      ).call
      redirect_to manager_products_path, notice:
        "The stock of #{@product.productable.type}s##{@product.id}" \
        " is replenished by #{amount_received}"
    else
      render :edit
    end
  end

  private

  def find_product
    Product.find(params[:id])
  end

  def product_params(productable_key:)
    return @product_params if @product_params

    @product_params = params.require(productable_key).require(:product).permit(:in_stock, :price)
    @product_params[:available] = @product_params[:in_stock]
    @product_params
  end
end

app/controllers/manager/search_orders_controller.rb
class Manager::SearchOrdersController < ManagerController
  def create
    date_in_numbers = SearchByDate.new(query: query).call

    if date_in_numbers.is_a? Hash
      redirect_to manager_orders_url(status: params[:status]), alert: date_in_numbers[:error]
      return
    end

    redirect_to manager_orders_url(search_by_date: date_in_numbers, status: params[:status])
  end

  private

  def query
    @query ||= params[:search][:query]
  end
end

app/controllers/manager_controller.rb
class ManagerController < AuthenticatedUserController
  before_action :check_manage_or_leader?

  private

  def check_manage_or_leader?
    return if current_user.manager? || current_user.leader?

    raise_access_error
  end
end

app/views/manager/orders/_product_set_fields.slim
.nested-fields
  = f.association :product, collection: @products
  = f.input :number, as: :integer
  = link_to_remove_association 'remove product set', f

app/views/manager/orders/index.slim
.col-12
  .d-inline-flex.align-items-center
    .h5 Sort:
    .btn-group.ml-1
      = link_to 'Closed', manager_orders_url(status: :closed, search_by_date: params[:search_by_date]),
        class: "btn btn-primary #{'active' if params[:status] == 'closed'}"
      = link_to 'Reserved', manager_orders_url(status: :reserved, search_by_date: params[:search_by_date]),
        class: "btn btn-primary #{'active' if params[:status] == 'reserved'}"
      = link_to 'Unreserved', manager_orders_url(status: :unreserved, search_by_date: params[:search_by_date]),
        class: "btn btn-primary #{'active' if params[:status] == 'unreserved'}"
      = simple_form_for :search, url: manager_search_order_path(status: params[:status]), html: { class: 'form-inline ml-2' }  do |f|
        = f.button :submit, 'Search by date', class: 'button btn btn-info'
        = f.input :query, label: false

  table.table.table-bordered.mt-2
    thead.thead-dark
      tr
        th.align-top #
        th.align-top Client
        th.align-top Date of saling
        th.align-top width='60%' Products
    tbody
      - @orders.each do |order|
        tr
          th
            = order.id
          td
            = link_to order.client.attributes_for_select, manager_client_path(order.client)
          td
            = order.date_of_saling.to_s(:long)
          td
            = render 'manager/orders/partials/products_table',
              product_sets: order.product_sets
        tr
          td colspan='4'
            .d-flex.justify-content-between.align-items-start
              = render 'manager/orders/partials/buttons_for_manage', order: order
              .p
                = "Status: #{order.status.capitalize}"
                .br
                = "Order summary price: $#{order.product_sets.sum(&:summary_price)}"

app/views/manager/orders/new.slim
.row.justify-content-md-center
  .col-4
    = simple_form_for(@order, url: manager_orders_path) do |f|
      = f.input :client_id, collection: @clients.to_a
      = f.input :date_of_saling
      = f.simple_fields_for :product_sets do |product_set|
        = render 'manager/orders/product_set_fields', f: product_set
      .links
        = link_to_add_association 'add product', f, :product_sets
      | Unloading place:
      #map
      = f.input :lng, as: :hidden, input_html: { 'data-behavior': 'lng' }
      = f.input :lat, as: :hidden, input_html: { 'data-behavior': 'lat' }
      = f.submit 'Open', class: 'btn btn-secondary'

= javascript_pack_tag 'components/orders/new/map'

app/views/manager/orders/show.slim
.container-fluid
  .row.justify-content-md-center.align-items-stretch
    .col-6
      .card.h-100
        .card-header
          | Order
        .card-body
          h5.card-title Client:
          p.card-text
            = link_to @order.client.attributes_for_select, manager_client_path(@order.client)
          h5.card-title Status:
          p.card-text
            = @order.status.capitalize
          h5.card-title Date of saling:
          p.card-text
            = @order.date_of_saling.to_s(:long)
          h5.card-title Place of saling:
          #map.mb-3.orders-show-map lng="#{@order.lng}" lat="#{@order.lat}"
          = link_to 'Back', :back, class: 'btn btn-primary'
    .col-6
      .card.h-100
        .card-header
          | Products in Order
        .card-body.d-flex.flex-column
          = render 'manager/orders/partials/products_table',
            product_sets: @order.product_sets
          h5.mb-0.card-title.font-weight-bold Summary price:
          p.card-text.font-weight-bold
            = "$#{@order.product_sets.sum(&:summary_price)}"
= javascript_pack_tag 'components/orders/show/map'