config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :home, only: :index
  root to: 'home#index'
  namespace :manager do
    resources :products, only: %i[new index edit update show]
    namespace :products do
      resources :pens
      resources :pencils
    end
    resources :orders
    resources :clients
    resource :search_order, only: %i[create]
  end

  namespace :client do
    resources :products, only: %i[new index edit update]
    namespace :products do
      resources :pens
      resources :pencils
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_sets
  belongs_to :client

  validates :product_sets, presence: true
  validates :date_of_saling, presence: true
  validate do |order|
    unless order.date_of_saling > DateTime.current.to_date
      order.errors.add(:date_of_saling, 'Date should be greater now!')
    end
  end

  validate do |order|
    product_ids = order.product_sets.flat_map(&:product_id)

    if product_ids != product_ids.uniq
      order.errors.add(:product_sets, "Please don't use the same products!")
    end
  end

  enum status: %i[opened unreserved reserved closed]

  accepts_nested_attributes_for :product_sets, reject_if: :all_blank, allow_destroy: true
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ManagerController
  def index
    @orders = Order.order(id: :desc).includes(:client, product_sets: { product: :productable })

    if params[:status]
      @orders = @orders.where(status: params[:status])
    else
      @orders = @orders.where.not(status: :closed)
    end

    if params[:search_by_date]
      @orders = @orders.where(date_of_saling: Date.parse(params[:search_by_date]))
    end
  end

  def new
    @order = Order.new
    @products = init_products
    @clients = init_clients
  end

  def create
    @order = Order.new(order_params)
    @clients = init_clients

    if @order.save
      redirect_to manager_orders_url
    else
      @products = init_products
      @clients = init_clients

      flash[:alert] = 'Please add products!' if @order.product_sets.blank?
      error_product_sets = @order.errors[:product_sets].first
      flash[:alert] = error_product_sets if error_product_sets
      render :new
    end
  end

  def show
    @order = Order.includes(product_sets: { product: :productable }).find(params[:id])
  end

  def update
    @order = find_order

    if @order.opened? && %w[unreserved reserved].include?(params[:status]) &&
      !current_user.leader?

      redirect_to manager_orders_url, alert: 'Access denied!'
    end

    ActiveRecord::Base.transaction do
      prev_status = @order.status
      unless @order.opened?
        if @order.update(status: params[:status])
          UpdateAvailableProducts.new(order: @order).call
        else
          flash['alert'] = 'Status invalid!'
        end
      else
        @order.update(status: params[:status])
      end

      if @order.closed? && prev_status == 'reserved'
        @order.product_sets.includes(:product).each do |product_set|
          product = product_set.product
          product.update(sold: product.sold.to_i + product_set.number,
                         in_stock: product.in_stock.to_i - product_set.number)
        end
      end
    end

    redirect_back(fallback_location: manager_orders_url)
  rescue ActiveRecord::RecordInvalid => e
    flash['alert'] = e.message
    redirect_back(fallback_location: manager_orders_url)
  end

  def destroy
    @order = find_order

    @order.destroy

    redirect_to manager_orders_url
  end

  private

  def order_params
    params.require(:order).permit(:'date_of_saling(1i)', :lng, :lat, :client_id,
                                  :'date_of_saling(2i)', :'date_of_saling(3i)',
                                  product_sets_attributes:
                                    [:product_id, :number, :_destroy])
  end

  def find_order
    Order.find(params[:id])
  end

  def init_products
    Product.all.includes(:productable).each_with_object({}) do |product, hash|
      hash[product.productable.attributes_for_select] = product.id
    end
  end

  def init_clients
    Client.all.each_with_object({}) do |client, hash|
      hash[client.attributes_for_select] = client.id
    end
  end
end

app/views/manager/orders/partials/_buttons_for_manage.slim
.btn-group
  = link_to 'Show', manager_order_path(order),
    class: 'button btn btn-info'
  - if current_user.leader? && order.opened?
    = button_to 'Confirm',
      manager_order_path(order, status: 'unreserved'),
      method: :patch, class: 'button',
      form_class: 'btn btn-primary'
  - if order.reserved?
    = button_to 'Unreserve',
      manager_order_path(order, status: 'unreserved'),
      method: :patch, class: 'button',
      form_class: 'btn btn-primary'
  - elsif order.unreserved?
    = button_to 'Reserve',
      manager_order_path(order, status: 'reserved'),
      method: :patch, class: 'button',
      form_class: 'btn btn-primary'
  - unless order.closed?
    = button_to 'Close', manager_order_path(order, status: 'closed'),
      method: :patch, class: 'button',
      form_class: 'btn btn-warning'
  = button_to 'Destroy',  manager_order_path(order),
    method: :delete, class: 'button',
    form_class: 'btn btn-danger'

app/views/manager/orders/partials/_products_table.slim
table.table
  thead
    tr
      th Name
      th Number
      th Summary price
  tbody
    - product_sets.find_each do |product_set|
      tr
        td
          = product_set.product.productable.attributes_for_select
        td
          = product_set.number
        td
          = "$#{product_set.summary_price}"