config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :home, only: :index
  root to: 'home#index'
  namespace :manager do
    resources :products, only: %i[new index edit update show]
    namespace :products do
      resources :pens
      resources :pencils
    end
    resources :orders
    resources :clients
    resource :search_order, only: %i[create]
  end

  namespace :client do
    resources :products, only: %i[new index edit update]
    namespace :products do
      resources :pens
      resources :pencils
    end
  end
end

app/views/layouts/partials/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  button.navbar-toggler aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo03" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand href="/" Home
  #navbarTogglerDemo03.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      - if current_user && (current_user.manager? || current_user.leader?)
        li.nav-item.active
          a.nav-link href="#{manager_products_path}"
            | Products
        li.nav-item.active
          a.nav-link href="#{new_manager_product_path}"
            | Add product
        li.nav-item.active
          a.nav-link href="#{manager_orders_path}"
            | Orders
        li.nav-item.active
          a.nav-link href="#{new_manager_order_path}"
            | Open order
        li.nav-item.active
          a.nav-link href="#{manager_clients_path}"
            | Clients
        li.nav-item.active
          a.nav-link href="#{new_manager_client_path}"
            | Add client

    .my-2.my-lg-0
      - if current_user
        = button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-info'
      - else
        = link_to 'Login', new_user_session_path, class: 'btn btn-outline-success'